/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#000000",
          50: "#fef2f2",
          100: "#fee2e2",
          200: "#fecaca",
          300: "#fca5a5",
          400: "#f87171",
          500: "#B21F24", // Premium Red
          600: "#9E161A",
          700: "#801114",
          800: "#630B0D",
          900: "#4D0507",
        },
        accent: {
          50: "#fff5f5",
          100: "#ffe3e3",
          200: "#ffd0d0",
          300: "#ffb3b3",
          400: "#ff8e8e",
          500: "#ff5c5c",
          600: "#f83a3a",
          700: "#d92222",
          800: "#b31919",
          900: "#941616",
        },
        "on-tertiary-container": "#d9c3c3",
        "inverse-primary": "#e5d2d2",
        "on-error-container": "#93000a",
        "surface": "#FAF9F9",
        "on-secondary-fixed-variant": "#5f1a1a",
        "background": "#FAF9F9",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1A1515",
        "tertiary": "#000000",
        "primary-container": "#151010",
        "on-secondary-fixed": "#2b0000",
        "charcoal-deep": "#151010",
        "primary-fixed": "#fcdcdc",
        "on-error": "#ffffff",
        "on-background": "#1A1515",
        "parchment-light": "#FAF9F9",
        "tertiary-fixed": "#ffd8d8",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#312e2e",
        "secondary": "#B21F24", // Premium Red
        "surface-variant": "#e3dedd",
        "tertiary-container": "#2b0000",
        "surface-container-high": "#eae5e4",
        "surface-container-low": "#f4efee",
        "primary-fixed-dim": "#e5d2d2",
        "on-primary-fixed-variant": "#584040",
        "secondary-fixed-dim": "#ecbebe",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e3dedd",
        "on-tertiary-fixed-variant": "#5e1e1e",
        "outline": "#7d7675",
        "secondary-container": "#fecbcb",
        "inverse-on-surface": "#f4f1f0",
        "tertiary-fixed-dim": "#e9b0b0",
        "slate-muted": "#E5E7EB",
        "surface-tint": "#705757",
        "surface-bright": "#FAF9F9",
        "on-primary-container": "#D1C7C7",
        "on-surface-variant": "#4c4544",
        "baked-gold": "#B21F24", // Premium Crimson Red
        "surface-container": "#efeae9",
        "outline-variant": "#cdc6c6",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#2b0000",
        "on-secondary-container": "#792e2e",
        "secondary-fixed": "#ffbaba",
        "surface-dim": "#dbd7d6",
        "on-primary-fixed": "#151010",
        "error": "#ba1a1a",
        "hearth-bronze": "#8B1619", // Dark hover crimson
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        "display-lg": ["Playfair Display"],
        "body-md": ["Montserrat"],
        "title-lg": ["Montserrat"],
        "headline-md": ["Playfair Display"],
        "label-lg": ["Montserrat"],
        "headline-lg-mobile": ["Playfair Display"],
        "label-sm": ["Montserrat"],
        "headline-lg": ["Playfair Display"],
        "body-lg": ["Montserrat"],
        "display-lg-mobile": ["Playfair Display"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "title-lg": ["20px", { lineHeight: "1.5", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "500" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
      },
      spacing: {
        gutter: "24px",
        "container-max": "1280px",
        "element-gap": "32px",
        "margin-desktop": "64px",
        "section-gap": "120px",
        "margin-mobile": "16px",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-in-out",
        "slide-up": "slideUp 0.5s ease-out",
        "bounce-slow": "bounce 2s infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
      },
    },
  },
  plugins: [],
};
